services:
  postgres_dev:
    image: postgres:18
    container_name: finance_tracker_postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql

  postgres_test:
    image: postgres:18
    container_name: finance_tracker_postgres_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_test
    volumes:
      - postgres_test_data:/var/lib/postgresql

volumes:
  postgres_dev_data:
  postgres_test_data:
